# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://muni-v.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joohye Park
user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff.
user_title: Software Engineer
email: joohyepark.dev@gmail.com
# twitter_username: lorem_ipsum
github_username: muni-v
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
